### ISSUE TITLE
Некорректная работа роутера при рендере родительских роутов

### ISSUE THREAD

**Issue by vkoktashev** [steroids/react#241]
Имеется следующий конфиг роутера:
<img width="719" alt="image" src="https://github.com/steroids/react/assets/24474150/32cc945a-9c02-427e-8d76-9da2f5289a0a">
Для отображения роутов используется компонент Tree
<img width="453" alt="image" src="https://github.com/steroids/react/assets/24474150/18125077-4d9c-49ee-a193-a6ef83089cc2">
Роуты в нем отображаются корректно, однако без указания exact: true для ROUTE_MENU и ROUTE_CONTENT при переходе на дочерние роуты ROUTE_CONTENT получаем ошибку
<img width="485" alt="image" src="https://github.com/steroids/react/assets/24474150/014fe160-6b2f-40ac-983d-afb94d2c1930">
В процессе выяснил, что это из-за того, что роутер пытается отрендерить ROUTE_MENU и ROUTE_CONTENT, а для них не указаны path и component. Но это контейнеры для набора других роутов и они не должны рендериться. Указание exact: true для них является скорее нелогичным хаком роутера, так как этот параметр отвечает за то, чтобы рендерить роуты только когда текущий path равен path роута, а для этих роутов path не указан. Указание только path приводит к другой проблеме - дочерние роуты не рендерятся.
Мне кажется нужно учесть роуты подобного вида и не пытаться их рендерить, если у них нет component, но есть дочерние items

**Comment by RaayNoff** [comment]
> Мне кажется нужно учесть роуты подобного вида и не пытаться их рендерить, если у них нет component, но есть дочерние items

Если нам нужно отрисовать категорию для дочерних маршрутов, как это должно будет выглядеть если мы запретим "контейнеру" рендериться при отсутствии компонента? Не хочется создавать пустой компонент под такие случаи или писать что-то дополнительно. 

Переход на дочерние маршруты, которые находятся в контейнерах, в которых нет свойства exact: true - всегда будет [приводить к отрисовке маршрута "контейнера"](https://stackoverflow.com/questions/49162311/react-difference-between-route-exact-path-and-route-path)

Если не нужно рендерить "контейнеры" и при этом нужны дочерние элементы то можно навешать соответствующие стили на Tree компонент.

Чтобы избежать непредвиденных переходов на маршруты контейнеров можно воспользоваться redirectTo пропом.

**Comment by vkoktashev** [comment]
> Переход на дочерние маршруты, которые находятся в контейнерах, в которых нет свойства exact: true - всегда будет [приводить к отрисовке маршрута "контейнера"](https://stackoverflow.com/questions/49162311/react-difference-between-route-exact-path-and-route-path)

Тут описывается поведение React router, а ошибка, из-за которой крашится страница, находится в стероидах. Я, когда пытался понять причину краша, добрался до кода, где наш роутер сам определяет, какие роуты рендерить, а какие нет. Ну и не думаю, что React router в принципе позволяет странице крашится, тут точно у нас проблема

> Чтобы избежать непредвиденных переходов на маршруты контейнеров можно воспользоваться redirectTo пропом.

Это не помогает в данном случае, страница всё ещё крашится

**Comment by Daria-Kuzminykh** [comment]
Решили проблему в [этом коммите](https://github.com/steroids/react/commit/94bec520c0808ee89bc54c63613b02252f256fd1)

**Comment by Daria-Kuzminykh** [comment]
Решили проблему в [этом коммите](https://github.com/steroids/react/commit/94bec520c0808ee89bc54c63613b02252f256fd1)
